# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logger.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'logger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clogger.proto\x12\x08loggerpb\"!\n\x03Log\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"-\n\nLogRequest\x12\x1f\n\x08logEntry\x18\x01 \x01(\x0b\x32\r.loggerpb.Log\"\x1d\n\x0bLogResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2E\n\nLogService\x12\x37\n\x08WriteLog\x12\x14.loggerpb.LogRequest\x1a\x15.loggerpb.LogResponseB\'Z%github.com/avkis/protos/golang/loggerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%github.com/avkis/protos/golang/logger'
  _globals['_LOG']._serialized_start=26
  _globals['_LOG']._serialized_end=59
  _globals['_LOGREQUEST']._serialized_start=61
  _globals['_LOGREQUEST']._serialized_end=106
  _globals['_LOGRESPONSE']._serialized_start=108
  _globals['_LOGRESPONSE']._serialized_end=137
  _globals['_LOGSERVICE']._serialized_start=139
  _globals['_LOGSERVICE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
